//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrantPermission
    {
        public int PermissionID { get; set; }
        public int UserID { get; set; }
        public string Description { get; set; }
    
        public virtual Admintrastor Admintrastor { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
