//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Permission
    {
        public int ID { get; set; }
        public int PermissionID { get; set; }
        public string MenuID { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
