//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostID { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public string Content { get; set; }
        public string Picture { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> ViewNo { get; set; }
        public string Status { get; set; }
        public Nullable<int> Admintrastor_UserID { get; set; }
    
        public virtual Admintrastor Admintrastor { get; set; }
        public virtual Category Category { get; set; }
    }
}
